title: "Inhyuk Hwang"
#description: "Welcome to my Jekyll site on GitHub Pages"
author: ""
#email: "gn121259@naver.com"
theme: minima

baseurl: ""
url: "https://gn121259.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - research.md
